print("Preparación: Precalienta el horno a 180C y engrasa/enharina tu molde para evitar que se pegue.")
print("Ingredientes a temperatura ambiente: Asegúrate de que huevos, mantequilla y leche estén a temperatura ambiente para evitar que la mezcla se corte.")
print("Acremar: Bate la mantequilla con el azúcar hasta obtener una crema suave y pálida")
print("Incorporar huevos: Agrega los huevos uno por uno a la mezcla de mantequilla, batiendo bien tras cada incorporacion.")
print("Tamizar ingredientes secos: Tamiza (pasa por un colador) la harina, el polvo para hornear, bicarbonato y/o cocoa para evitar grumos.")
print("Mezclar la masa: Incorpora los ingredientes secos a la mezcla liquida poco a poco, alternando con la leche. Mezcla con movimientos envolventes y evita batir en exceso para que no quede duro.")
print("Hornear: Vierte la mezcla en el molde, alisa la superficie y hornea durante 30-40 minutos.")
print("Verificación: Pincha el centro del pastel con un palillo; si sale limpio, está listo.")
print("Enfriar: Deja reposar el pastel en el molde por 10 minutos, luego desmolda y deja enfriar completamente sobre una rejilla antes de decorar")
